const api = {
  // 采集器列表分页查询
  collectorList: '/platform/opcCollector/use/page',
  // 采集器修改、删除、详情
  collectorAction: '/platform/opcCollector/',
  // 控制采集器开关
  collectorControl: '/platform/opcCollector/control/',
  // 采集器具分页列表查询
  collectorMeterPage: '/platform/opcMeter/page',
  // 采集器具删除、新增、修改
  collectorMeterAction: '/platform/opcMeter/',
  // 查询该单位下待导入的采集器具
  getNeedExportMeters: '/platform/opcMeter/toImport',
  // 采集点分页列表查询
  collectorPointPage: '/platform/opcItem/page/',
  // 删除、新增采集点
  collectorPointAction: '/platform/opcItem/',
  // 获取所有采集点
  collertorPointList: '/platform/opcItem/list/',
  // 采集器列表
  collectorsData: '/platform/opcCollector/list',
  // 报警点分页列表查询
  getWarningPage: '/platform/opcWarn/page/',
  // 报警点删除、添加
  warnPointAction: '/platform/opcWarn/',
  // 实时数据大屏-单位下器具总数
  getMeterCount: '/platform/opcMeter/allMeterCount/',
  // 实时数据大屏-单位下采集点总数
  getCollectorPointCount: '/platform/opcItem/allCount/',
  // 实时数据大屏-单位下激活器具总数
  getActivateMeterCount: '/platform/opcMeter/allActiveCount/',
  // 实时数据大屏-获取饼图数据器具总数、待维修、待保养数量
  getMeterPieData: '/platform/opcMeter/meterCountByOrgId/',
  // 器具关联采集点报警点查询
  getMeterCollectorRelation: '/platform/view/opcMeter/itemWarn/',
  // 单位关联采集点报警点
  getOrgCollertorRelationList: '/platform/opcMeter/itemWarn/list/'
}
export default api
