const api = {
  // 使用单位-委托管理-委托单列表
  enterpriseOrderList: '/platform/useUnitOrder/page',
  // 使用单位-委托管理-通过id查询委托单详情
  enterpriseOrderDetailById: '/platform/useUnitOrder/',
  // 使用单位-委托管理-确认收货
  enterpriseReceiveGoods: '/platform/useUnitOrder/confirm/',
  // 使用单位-委托管理-立即付款
  enterpriseToPay: '/platform/useUnitOrder/payment',
  // 使用单位-委托管理-修改委托单付款状态(一口价为0时调用)
  changeOrderStatus: '/platform/useUnitOrder/statusModify',
  // 使用单位-委托管理-创建通联个人会员
  createUnitPayAccount: '/platform/payUser/createIndividualMember',
  // 通联个人会员获取手机验证码
  getPersonalMemberCode: '/platform/payUser/sendVerificationCode',
  // 通联个人会员绑定手机号
  personalMemberBiddingPhone: '/platform/payUser/bindPhone',
  // 通联个人会员状态
  personalMemberStatus: '/platform/payUser/individualAccountStatus',
  // 立即付款
  personMemberPayment: '/platform/useUnitOrder/agentCollectApply',
  // 使用单位-委托管理-取消委托单
  enterpriseCancelOrder: '/platform/useUnitOrder/cancel/',
  // 检定机构-委托单管理-委托单列表
  calibrationOrderList: '/platform/viOrder/page',
  // 检定机构-委托单管理-通过id查询委托单详情
  calibrationOrderDetailById: '/platform/viOrder/',
  // 检定机构-委托单管理-处理委托单
  calibrationHandleOrder: '/platform/dealOrder',
  // 检定机构-委托单管理-确认收货
  calibrationReciveGoods: '/platform/viOrder/confirm/',
  // 检定机构-委托单管理-工作台详情
  calibrationWorkStage: '/platform/viOrder/workbench/',
  // 检定机构-委托单管理-送检器具是否检校
  calibrationIsMeterCheck: '/platform/viOrderMeter/calibration',
  // 检定机构-委托单管理-工作台是否维修
  calibrationIsRepaire: '/platform/viOrderMeter/maintain',
  // 检定机构-委托单管理-修改工作台检校服务
  calibrationUpdateService: '/platform/viOrder/service',
  // 检定机构-委托单管理-删除检校服务
  calibrationDeleteService: '/platform/viOrderService/',
  // 检定机构-委托单管理-修改工作台备注
  calibrationUpdateRemark: '/platform/viOrder/remark',
  // 检定机构-委托单管理-新增证书、编辑证书、 删除证书
  calibrationCertificateAction: '/platform/certificate/',
  // 检定机构-委托单管理-修改工作台维修金额
  calibrationUpdateAmount: '/platform/viOrder/amount',
  // 检定机构-委托单管理-修改工作台一口价
  calibrationUpdateBuyout: '/platform/viOrder/buyout',
  // 检定机构一口价置空
  buyOutSetNull: '/platform/viOrder/buyoutSetNull',
  // 检定机构-委托单管理-新增检校服务
  calibrationAddService: '/platform/calibrationService',
  // 检定机构添加物流信息
  calibrationAddExpressInfo: '/platform/viOrder/logistics',
  // 委托单详情-委托单节点信息
  orderNodeName: '/platform/nodeName',
  // 检定机构--上传委托单协议--删除委托单协议
  uploadProtocol: '/platform/viOrder/protocol/',
  // 检定机构--一键免除费用
  orderFree: '/platform/viOrder/oneClickFree',
  // 委托单免除费用
  orderFreeById: '/platform/viOrder/feeWaiver',
  // 获取待付款数量
  getNeedPayOrderCount: '/platform/viOrder/quantityToBePaid',
  // 发送委托单数据到语墨
  sendToYumo: '/platform/sendToYumo'
}
export default api
