const api = {
  // 子账号分页列表
  zqsubUserPage: '/platform/subUser/page',
  // 删除子账号
  zqdeleteSubuser: '/platform/subUser/',
  // 子账号重置密码
  zqresetPassword: '/platform/subUser/resetPassword/',
  // 新增子账号
  zqsaveSubUser: '/platform/subUser',
  // 修改子账号
  zqeditSubUser: '/platform/subUser',
  // 获取部门
  zqDepartment: '/platform/sysDepartment/page',
  // 删除部门
  zqdeleteDepartment: '/platform/sysDepartment/',
  // 新增部门
  zqsysDepartment: '/platform/sysDepartment',
  // 修改部门
  zqeditDepartment: '/platform/sysDepartment',
  // 文件管理
  // 文件管理列表分页
  zqFilePage: '/platform/file/page',
  // 根据文件id获取文件可见人
  zqVisiblePersonList: '/platform/file/visiblePersonList/',
  // 根据文件id获取文件审批人
  zqApproverList: '/platform/file/approverList/',
  // 根据单位id查询组织机构树
  zqOrgDeptUserTree: '/platform/file/orgDeptUserTree',
  // 发布文件
  zqFileAdd: '/platform/file',
  // 根据文件id获取文件指派人
  zqDesignatorList: '/platform/file/designatorList/',
  // 删除文件
  zqDeleteFile: '/platform/file/',
  // 指派
  zqDesignate: '/platform/file/designate',
  // 根据文件id获取审核弹窗中的内容
  zqViewFile: '/platform/file/',
  // 审核通过
  zqCheckPass: '/platform/file/checkPass',
  // 审核驳回
  zqCheckReject: '/platform/file/checkReject',
  // 查看驳回原因
  zqRejectReason: '/platform/file/rejectReason/'
}
export default api
