export { default as Heading } from './Heading'
export { default as Sidebar } from './Sidebar/index.vue'
export { default as Menu } from './Menu'
export { default as AppMain } from './AppMain'
export { default as Footer } from './Footer'
export { default as TagsView } from './TagsView/index.vue'
