const api = {
  // 检校服务-服务类型
  // 服务类型列表
  serviceList: '/platform/view/meterType/page',
  // 服务类型增删改查
  serviceTypeAction: '/platform/meterType/',
  // 运营人员-检校服务-委托管理-委托单列表
  adminConsoleOrderList: '/platform/vccsOrder/page',
  // 运营人员-检校服务-委托管理-通过id查询委托单详情
  adminConsoleOrderListById: '/platform/vccsOrder/',
  // 运营人员-获取应用服务列表（运营端）
  clientServiceList: '/platform/applicationService/page',
  // 运营人员-获取所有应用服务列表（运营端）
  clientServiceAll: '/platform/applicationService/list',
  // 运营人员-新增、删除、修改应用服务（运营端）
  clientService: '/platform/applicationService/',
  // 获取所有服务列表 （运营端根据orgId获取）
  byOrgId: '/platform/applicationServicePurchaseDetail/byOrgId',
  // 实名认证查看添加提交idis
  realNameCheckIdis: '/platform/sysOrganization/organizationDetail/',
  // 运营端台账管理列表
  allMeter: '/platform/allMeter/page',
  // 运营端采集器管理列表
  collector: '/platform/allOpcCollector/page',
  // 运营端采集器审核
  auditCheck: '/platform/opcCollector/check',
  // 获取角色列表
  clientRoleList: '/platform/view/roleList',
  // 运营端-激活码管理列表
  activationCodePage: '/platform/activationCode/page',
  // 运营端-新增、修改、删除激活码
  activationCodeAction: '/platform/activationCode/',
  // 运营端-停用激活码
  pauseActivationCode: '/platform/deactivationActivationCode/',
  // 激活码绑定单位列表
  activateCodeBindingOrg: '/platform/activationCodeBinding/',
  // 获取可应用服务列表
  getAppList: '/platform/view/application/list',
  // 公共-激活码管理-激活码列表
  commonActivateCodePage: '/platform/activationCode/list',
  // 公共-激活码管理-查询激活码可激活应用
  activateApplication: '/platform/activateApplication/',
  // 公共-激活码管理-移除某个单位使用激活码
  removeOrgActivateCode: '/platform/activationCodeBinding',
  // 公共-激活码管理-判断是否有权限激活应用服务
  HasApplicationService: '/platform/applicationService/judgeToActivation',
  // 公共-激活码管理-激活码激活应用服务
  activationAppService: '/platform/activationCode/activationApplicationService',
  // 根据id查询激活码详情
  activateCodeDetail: '/platform/activationCode/',
  // 公共-已购买服务列表
  hasBuyApps: '/platform/purchasedServices/list',
  // 试用服务
  tryService: '/platform/activationCode/trialService/',
  // 获取可激活时长
  getActivateDurs: '/platform/activateApplication/activateDuration',
  // 检校区域分页查询列表
  calibrationAreaPage: '/platform/vccsInstitutionsArea/page',
  // 检校区域增删改查
  calibrationAreaAction: '/platform/vccsInstitutionsArea/',
  // 会员信息-快速注册
  inputOrgInfo: '/platform/inputOrgInfo',
  // 未实名用户分页列表查询
  getUnRealnameUserList: '/platform/sysUser/noIdentificationUser/page',
  // 待续费用户分页列表查询
  getRenewUserList: '/platform/sysOrganization/renewOrg/page',
  // 用户最新登录分页列表统计
  getActiveUserList: '/platform/statistics/lastLoginInfo/page',
  // 用户活跃度统计
  getAllUserActive: '/platform/statistics/livenessUser',
  // 线下订单提交
  submitOfflineOrder: '/platform/offlineOrder',
  // 获取单位认证状态
  getOrgCertiFileStatus: '/platform/organization/certificationStatusById',
  // 身份证正面上传（人像）
  uploadIdCardFront: '/platform//legalCard/upload',
  // 身份证反面上传
  uploadIdCardBack: '/platform/legalCardObverse/upload',
  // 影印件提交通联
  submitCertiFileUnionPay: '/platform/organization/idcard',
  // 到期服务状态查询
  getServiceExpireDruing: '/platform/expireOrExpiredService',
  // 导出用户最新登陆记录
  getUserLastedLogin: '/platform/statistics/lastLoginInfo/list/export',
  // 导出待续费记录
  getRenewRecordFile: '/platform/sysOrganization/renewOrg/list/export',
  // 获取服务名称数据字典
  getServiceNameByDic: '/platform/view/applicationService',
  // 服务名称获取服务时长
  getServiceDurBySerName: '/platform/view/applicationName/',
  // 修改用户信息申请企业前缀字段
  updateUserIsApplyPrefix: '/platform/sysOrganization/applyPrefix/',
  // 提交仪表审核
  submitybRealname: '/platform/sysUserOrganization/reIdentification'
}
export default api
